#!/bin/bash

# Set these values
# Generate the password hash with "RetroShare-nogui -G"
SSH_PORT=0000 # Do not use the same prot as retroshare!
SSH_USERNAME=ServerUser
SSH_PASSWDHASH=PasswordHash
# Protect this file it will contain your GPG password!
GPG_PASS=GpgPass

# For instructions see the retroshare wiki
# http://retroshare.sourceforge.net/wiki/index.php/Documentation:retroshare-nogui

# Automatically start RetroShare-nogui in a screen session
screen -dmS RetroScreen
screen -S "RetroScreen" -p 0 -X stuff "/usr/bin/expect -c 'spawn RetroShare-nogui -c /home/retrouser/.retroshare -C -X -S $SSH_PORT -L $SSH_USERNAME -P $SSH_PASSWDHASH&; expect \"(Generated by RetroShare)\"; send \"$GPG_PASS\r\"; interact' $(printf \\r)"


# If you want to manually start RetroShare-nogui and type your password, comment out the previous line and run this command in the screen terminal manually.
# RetroShare-nogui -c /home/retrouser/.retroshare -C -X -S $SSH_PORT -L $SSH_USERNAME -P $SSH_PASSWDHASH&
